### ISSUE TITLE
how to set defualt selected country

### ISSUE THREAD

**Issue by SunryTeang** [mukeshsolanki/country-picker-android#56]

**Comment by mukeshsolanki** [comment]
to set a list of countries you can call `countryPicker.getAllCountries()` with will return a list of all the countries and you simply copy the object you want to display and then call the `countryPicker.setCountries()` method

**Comment by SunryTeang** [comment]
thank you

**Comment by mukeshsolanki** [comment]
There is no good reason for this

**Comment by matteobucci** [comment]
> There is no good reason for this

Hi @mukeshsolanki, I think there is one. We implemented this library (very well done, congrats) in an app where we need to know the country of residence and we already have some information about them.
Since the >95% of our users is going to select Italy as a country, it makes no sense for them to start from Afganistan each time. Furthermore, if they need to edit their data, we should show them the country they have already selected.

I hope that was clear :smile:
